#!/bin/sh
# .git/hooks/pre-push

# Get the name of the branch being pushed
branch_name=$(git symbolic-ref --short HEAD)

# Define branches that should not be pushed
blocked_branches="main master"

# Check if the current branch is one of the blocked branches
if echo "$blocked_branches" | grep -w "$branch_name" > /dev/null; then
    echo "Error: Pushing directly to '$branch_name' is not allowed."
    echo "Please create a new branch for your changes."
    exit 1
fi

# Allow the push if not blocked
exit 0
